errors <- function() {
  list(
    status.code = c(
      "301",
      "400",
      "400",
      "400",
      "400",
      "400",
      "400",
      "400",
      "400",
      "400",
      "400",
      "400",
      "401",
      "401",
      "403",
      "404",
      "405",
      "409",
      "429",
      "500",
      "500"
    ),
    text = c(
      "PERMANENTLY_MOVED",
      "ACTION_NOT_PROCESSED",
      "ARGUMENTS_ERROR",
      "BAD_CONTINUATION_TOKEN",
      "BAD_PAGE",
      "BAD_REQUEST",
      "INVALID_ARGUMENT",
      "INVALID_AUTH",
      "INVALID_AUTH_HEADER",
      "INVALID_BATCH",
      "INVALID_BODY",
      "UNSUPPORTED_OPERATION",
      "ACCESS_DENIED",
      "NO_AUTH",
      "NOT_AUTHORIZED",
      "NOT_FOUND",
      "METHOD_NOT_ALLOWED",
      "REQUEST_CONFLICT",
      "HIT_RATE_LIMIT",
      "EXPANSION_FAILED",
      "INTERNAL_ERROR"
    ),
    description = c(
      "Resource must be retrieved from a different URL.",
      "Requested operation not processed.",
      "There are errors with your arguments.",
      "Invalid continuation token passed.",
      "Page number does not exist or is an invalid format (e.g. negative).",
      "The resource you’re creating already exists.",
      "Invalid argument value passed.",
      "Authentication/OAuth token is invalid.",
      "Authentication header is invalid.",
      "Batched request is missing or invalid.",
      "A request body that was not in JSON format was passed.",
      "Requested operation not supported.",
      "Authentication unsuccessful.",
      "Authentication not provided.",
      "User has not been authorized to perform that action.",
      "Invalid URL.",
      "Method is not allowed for this endpoint.",
      "Requested operation resulted in conflict.",
      "Hourly rate limit has been reached for this token. Default rate limits are 2,000 calls per hour.",
      "Unhandled error occurred during expansion; the request is likely to succeed if you don’t ask for expansions, but contact Eventbrite support if this problem persists.",
      "Unhandled error occurred in Eventbrite. contact Eventbrite support if this problem persists."
    )
  )
}

